Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113600
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'strip'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113584
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = str(value.lower().strip())
                ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113618
Internal Server Error: /accounts/promote-to-superuser/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/views.py", line 181, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/account/serializers.py", line 118, in validate
    value = value.lower().strip()
            ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lower'
"POST /accounts/promote-to-superuser/ HTTP/1.1" 500 113605
Internal Server Error: /blogs/add-category
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/blogs/add-category/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /blogs/add-category HTTP/1.1" 500 78236
Internal Server Error: /blogs/upload-blog/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 497, in to_internal_value
    for field in fields:
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `user` is not valid for model `Blog` in `blog.serializers.UploadBlogSerializer`.
"POST /blogs/upload-blog/ HTTP/1.1" 500 151905
Internal Server Error: /blogs/upload-blog/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 497, in to_internal_value
    for field in fields:
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1105, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1251, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1369, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `user` is not valid for model `Blog` in `blog.serializers.UploadBlogSerializer`.
"POST /blogs/upload-blog/ HTTP/1.1" 500 151905
Internal Server Error: /blogs/delete-category/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 221, in delete
    return self.destroy(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 90, in destroy
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 87, in get_object
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/Kelassor/blog/views.py", line 44, in get_queryset
    return CategoryBlog.objects.filter(uploaded_by=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'uploaded_by' into field. Choices are: blog, id, name, slug
"DELETE /blogs/delete-category/ HTTP/1.1" 500 157946
Internal Server Error: /blogs/delete-category/
Traceback (most recent call last):
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 221, in delete
    return self.destroy(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 90, in destroy
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "/home/amirykta/Documents/Final_Project2 DRF/env/lib/python3.12/site-packages/rest_framework/generics.py", line 92, in get_object
    assert lookup_url_kwarg in self.kwargs, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected view DeleteCategoryBlogView to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
"DELETE /blogs/delete-category/ HTTP/1.1" 500 110304
